### ISSUE TITLE
On Wrong React code Codepen freezes browser (and eventually results in system crash)

### ISSUE THREAD

**Issue by palerdot** [CodePen/InfiniteLoopBuster#3]
Consider this snippet
https://codepen.io/gaearon/pen/aWWQOG?editors=0010

Just try writing 
`<button className="square" onClick={this.setState({value: 'X'})>`

instead of
`<button className="square" onClick={() => this.setState({value: 'X'})}>`

Codepen just auto refreshes when typing the first statement, hangs eventually leading to browser and system crash (Latest chrome, Ubuntu 16).

I'm not sure if this is the right place to report this, but this is really a pain. The code is not even saved, and codepen just starts refreshing while typing and just crashes.

**Comment by chriscoyier** [comment]
I confirmed this. Here's a video: http://d.pr/v/pimYfd/1cO5SbeE

This is just JavaScript executing and React freaking out about the code it sees. I don't think this infinite loop catcher could step in here. What would help is if we didn't refresh JavaScript until your cursor has left the line it's currently typing on. We used to to that, but apparently not anymore, so I'll open a ticket on our side for that.

**Comment by EvanFreeman** [comment]
What's going on with this? I can't even open existing pens due to this issue.

**Comment by chriscoyier** [comment]
If you need to stop JS because of broken code:

https://blog.codepen.io/documentation/features/turn-off-javascript-in-previews/

**Comment by EvanFreeman** [comment]
My hero! That got me through thank you.
