### ISSUE TITLE
codepen frees dashboard

### ISSUE THREAD

**Issue by ClaytonSibanda** [CodePen/InfiniteLoopBuster#7]
I am learning react so i wrote wrong code for one my event handlers on react, and this made the whole browser page to freeze. I also cannot acces my codepen dashboard because of that.I cant send you the link to the proplematic pen because i cant even open any of the pens on the dashboard. my user name is Clayton Sibanda. i dont know if you guys can help with that

**Comment by chriscoyier** [comment]
This should help: https://blog.codepen.io/documentation/features/turn-off-javascript-in-previews/
